# Encoding
## Label Encoding

In [2]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

[0 1 4 5 3 3 2 2]


In [9]:
labels = encoder.fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [3]:
# mapping된 클래스를 리스트로 알 수 있음
print(encoder.classes_)

['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [5]:
# 숫자 -> 문자로 변경하는 방법
print(encoder.inverse_transform([4,5,2,0,1,1,3,3]))

['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


## One-Hot Encoding
- 반드시 2차원 데이터 사용해야함 
- reshape(-1,1) : 데이터 1개씩 들어있는 리스트들로 변경
- 값들에 대하여 true인 값만 1

In [7]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
items = np.array(items).reshape(-1,1) 

oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

print("원-핫 인코더 데이터")
print(oh_labels.toarray())
print("원-핫 인코더 데이터 차원")
print(oh_labels.shape)

원-핫 인코더 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코더 데이터 차원
(8, 6)


## Pandas get_dummies
- One Hot Encoder를 좀 더 쉽게 사용하는 방법

In [10]:
import pandas as pd

df = pd.DataFrame({'item':['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
df.head()

item
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기

In [11]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0

# Scaling
## feature scaling by StandardScaler

In [3]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print("feature들의 평균")
print(iris_df.mean())
print("\nfeature들의 분산값")
print(iris_df.var())

feature들의 평균
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)
print("feature 평균 값")
print(iris_df_scaled.mean())
print("\nfeature 분산 값")
print(iris_df_scaled.var())

feature 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


## min max Scaler

In [9]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data= iris_scaled, columns=iris.feature_names)

print("min값")
print(iris_df_scaled.min())
print("\nmax값")
print(iris_df_scaled.max())

min값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

max값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


## Scaler 적용시 주의사항

- test와 train을 따로 적용시키면 안됨
- 함께 묶여있을 때 적용하는 것이 가장 좋지만, 만약 test와 train이 철저히 분리된 상황이라면 train으로 fit되어있는 Scaler를 사용해야함.(fit_transform을 사용하는 것에 있어서 제한이 있음)

In [11]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

In [13]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print("적용전 train_array : ",train_array)
print("적용후 train_array :",train_scaled)

적용전 train_array :  [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
적용후 train_array : [[0. ]
 [0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]
 [0.6]
 [0.7]
 [0.8]
 [0.9]
 [1. ]]


In [14]:
scaler.fit(test_array)
test_scaled = scaler.transform(test_array)

print("적용전 test_array : ",test_array)
print("적용후 test_array :",test_scaled)

적용전 test_array :  [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
적용후 test_array : [[0. ]
 [0.2]
 [0.4]
 [0.6]
 [0.8]
 [1. ]]


In [15]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print("적용전 train_array : ",train_array)
print("적용후 train_array :",train_scaled)

test_scaled = scaler.transform(test_array)
print("적용전 test_array : ",test_array)
print("적용후 test_array :",test_scaled)

적용전 train_array :  [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
적용후 train_array : [[0. ]
 [0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]
 [0.6]
 [0.7]
 [0.8]
 [0.9]
 [1. ]]
적용전 test_array :  [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
적용후 test_array : [[0. ]
 [0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]]
