In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [3]:
model = nn.Linear(1,1) # input dim, output dim

In [4]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [5]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    prediction = model(X_train)
    
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 9.427197
Epoch  100/2000 Cost: 0.007141
Epoch  200/2000 Cost: 0.004413
Epoch  300/2000 Cost: 0.002727
Epoch  400/2000 Cost: 0.001685
Epoch  500/2000 Cost: 0.001041
Epoch  600/2000 Cost: 0.000643
Epoch  700/2000 Cost: 0.000398
Epoch  800/2000 Cost: 0.000246
Epoch  900/2000 Cost: 0.000152
Epoch 1000/2000 Cost: 0.000094
Epoch 1100/2000 Cost: 0.000058
Epoch 1200/2000 Cost: 0.000036
Epoch 1300/2000 Cost: 0.000022
Epoch 1400/2000 Cost: 0.000014
Epoch 1500/2000 Cost: 0.000008
Epoch 1600/2000 Cost: 0.000005
Epoch 1700/2000 Cost: 0.000003
Epoch 1800/2000 Cost: 0.000002
Epoch 1900/2000 Cost: 0.000001
Epoch 2000/2000 Cost: 0.000001


In [6]:
new_var =  torch.FloatTensor([[4.0]]) 
pred_y = model(new_var)
print(pred_y)

tensor([[8.0018]], grad_fn=<AddmmBackward0>)


In [7]:
print(list(model.parameters()))

[Parameter containing:
tensor([[2.0010]], requires_grad=True), Parameter containing:
tensor([-0.0023], requires_grad=True)]


## 다중선형회귀

In [8]:
X_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [9]:
model = nn.Linear(3,1)

In [10]:
optimizer = torch.optim.SGD(model.parameters(),lr = 1e-5)

In [11]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    prediction = model(X_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 22584.841797
Epoch  100/2000 Cost: 0.840386
Epoch  200/2000 Cost: 0.806277
Epoch  300/2000 Cost: 0.773955
Epoch  400/2000 Cost: 0.743331
Epoch  500/2000 Cost: 0.714319
Epoch  600/2000 Cost: 0.686823
Epoch  700/2000 Cost: 0.660761
Epoch  800/2000 Cost: 0.636061
Epoch  900/2000 Cost: 0.612671
Epoch 1000/2000 Cost: 0.590487
Epoch 1100/2000 Cost: 0.569477
Epoch 1200/2000 Cost: 0.549559
Epoch 1300/2000 Cost: 0.530682
Epoch 1400/2000 Cost: 0.512793
Epoch 1500/2000 Cost: 0.495839
Epoch 1600/2000 Cost: 0.479769
Epoch 1700/2000 Cost: 0.464530
Epoch 1800/2000 Cost: 0.450107
Epoch 1900/2000 Cost: 0.436419
Epoch 2000/2000 Cost: 0.423448


In [12]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.0463, 0.6626, 0.3008]], requires_grad=True), Parameter containing:
tensor([0.4789], requires_grad=True)]
